[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[dependencies]
rand = "0.8.5"

[dev-dependencies]
insta = "1.34.0"
